.gitignore, src/main/java/com/purbon/kafka/topology/TopologyCustomDeserializer.java, src/main/java/com/purbon/kafka/topology/TopologySerdes.java, src/main/java/com/purbon/kafka/topology/model/Topology.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/resources/descriptor-with-others.yml, src/test/resources/descriptor.yaml
This PR adds dynamic attributes as first level. This will enable the possibility for teams to customise their top level descriptors.
With a descriptor like:
```yaml
team: "team"
source: "source"
foo: "foo"
bar: "bar"
zet: "zet"
projects:
- name: "foo"
```
a prefix will be generated like:
_team.source.foo.bar.zet_
while with a descriptor like:
```yaml
team: "team"
source: "source"
projects:
- name: "foo"
```
a prefix like _team.source_ will be used.
Fix #8
=> Add dynamic top level attributes to extend the descriptor file syntax

pom.xml
To resolve warnings from maven:
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 113, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
=> Add version number to maven-compiler-plugin

release/docker/Dockerfile, release/docker/build.sh
Adds an initial set of scripts and dockerfile for releasing docker images into docker hub. This images are very useful for building CI/CD pipelines or to be used inside kubernetes.
=> Add release mechanism for docker images with the kafka topology builder

changelog.md, src/main/java/com/purbon/kafka/topology/TopologyBuilderAdminClient.java, src/main/java/com/purbon/kafka/topology/serdes/ProjectCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/resources/descriptor-only-topics.yaml
Fix parser problem with non required parameters, such as the ones for the acls where an empty array had to be in place, now all principals for acls if not required can be ignored and will have no effect.
fixes #35
=> Fixes problems with empty fields in the acls principals list

changelog.md, src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/AccessControlProvider.java, src/main/java/com/purbon/kafka/topology/KafkaTopologyBuilder.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderAdminClient.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/java/com/purbon/kafka/topology/api/mds/MDSApiClient.java, src/main/java/com/purbon/kafka/topology/exceptions/ConfigurationException.java, src/main/java/com/purbon/kafka/topology/roles/AdminRoleRunner.java, src/main/java/com/purbon/kafka/topology/roles/RBACProvider.java, src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/java/com/purbon/kafka/topology/AccessControlWithRBACTest.java, src/test/java/com/purbon/kafka/topology/AdminRoleRunnerTest.java, src/test/java/com/purbon/kafka/topology/KafkaTopologyBuilderTest.java, src/test/java/com/purbon/kafka/topology/TopologyBuilderConfigTest.java, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/RBACPRoviderRbacIT.java
This PR adds validation and meaninful errors back for missing RBAC configuration requirements. If you miss one of the required properties, for example the connect cluster ID an error like this will be shown:
```bash
$>  java -jar target/kafka-topology-builder-jar-with-dependencies.jar  --brokers localhost:9094 --clientConfig example/topology-builder-rbac.properties --topology example/descriptor-with-rbac.yaml
log4j:WARN No appenders could be found for logger (org.apache.kafka.clients.admin.AdminClientConfig).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" com.purbon.kafka.topology.exceptions.ConfigurationException: Required clusterID …
```
=> Validate required parameters for the RBAC configuration 

changelog.md, docker/sasl/docker-compose.yml, src/main/java/com/purbon/kafka/topology/KafkaTopologyBuilder.java, src/main/java/com/purbon/kafka/topology/TopicManager.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderAdminClient.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/java/com/purbon/kafka/topology/api/mds/MDSApiClient.java, src/main/java/com/purbon/kafka/topology/api/mds/Response.java, src/test/java/com/purbon/kafka/topology/TopicManagerTest.java, src/test/java/com/purbon/kafka/topology/integration/MDSApiClientRbacIT.java, src/test/java/com/purbon/kafka/topology/integration/TopicManagerIT.java
Add an option to not delete internal topics, including an option configure rules to filter internal topics that can't not be removed config with  _kafka.internal.topic.prefixes_, by default this filters all topics starting with underscore. Users can configure more than one filter in the property file.
fixes #39
=> Amend problem with deleting internal topics

changelog.md, example/descriptor.yaml, src/main/conf/topology-builder.properties, src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/AccessControlProvider.java, src/main/java/com/purbon/kafka/topology/KafkaTopologyBuilder.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderAdminClient.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/java/com/purbon/kafka/topology/model/users/Connector.java, src/main/java/com/purbon/kafka/topology/model/users/SchemaRegistry.java, src/main/java/com/purbon/kafka/topology/roles/AdminRoleRunner.java, src/main/java/com/purbon/kafka/topology/roles/RBACProvider.java, src/main/java/com/purbon/kafka/topology/roles/SimpleAclsProvider.java, src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/java/com/purbon/kafka/topology/AdminRoleRunnerTest.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/TopicManagerIT.java, src/test/resources/descriptor.yaml
This PR makes internal topics of Kafka Connect, Schema Registry and Confluent Control Center configurable. By introducing this, users can now handle non-standard instances of Schema Registry or having for example more than a single Kafka Connect cluster (situation more than common).
fixes #46 
@jeanlouisboudart thoughts?
=> Make internal topics and groups configurable for Kafka Connect, Schema Registry and Control center

changelog.md, docs/index.rst, docs/what-can-you-do.rst, src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/AccessControlProvider.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderAdminClient.java, src/main/java/com/purbon/kafka/topology/model/users/Consumer.java, src/main/java/com/purbon/kafka/topology/roles/RBACProvider.java, src/main/java/com/purbon/kafka/topology/roles/SimpleAclsProvider.java, src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/resources/descriptor.yaml
This pull request add the capability to specify custom consumer groups per each consumer principal or use as default the "*" as catch all method.
@sknop This is what we spoke offline the other day, does this fits your thoughts?
=> Specify custom consumer groups per consumer principal

README.md
Updated comments in the example to reflect the recent change from "team" to "context".
=> Example: team.source.foo.foo -> context.source.foo.foo

changelog.md, src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/AccessControlProvider.java, src/main/java/com/purbon/kafka/topology/ClusterState.java, src/main/java/com/purbon/kafka/topology/actions/ClearAcls.java, src/main/java/com/purbon/kafka/topology/roles/RBACProvider.java, src/main/java/com/purbon/kafka/topology/roles/SimpleAclsProvider.java, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java
This PR fixes issue #72. As explained in the issue the problem was caused by the direct use of ClusterState in ClearAcls action for which bindings to remove. So solved it by refactoring ClearAcls to just take a list of bindings to be deleted - a copy of the list of bindings in ClusterState that is. 
Also replaced the integration test on this feature to simulate topology changes that should result in acl removals.
As a side note: I think it would be better to not delete all acls and then adding them again. But that can be discussed later :-)
=> Fix bug on removal of acls 

.gitignore, changelog.md, scripts/run-docker-run-cmd.sh, src/main/java/com/purbon/kafka/topology/KafkaTopologyBuilder.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/java/com/purbon/kafka/topology/actions/topics/SyncTopicAction.java, src/test/resources/client-config-redis.properties, src/test/resources/client-config.properties
Right now is possible to pass to the Schema Registry client configs passed in the property file for the schema registry client configs. This properties should be prefixed with _schema.registry_ as described in the Kafka Topology Builder class.
fixes #91
=> Pass config values to the Schema Registry Client

changelog.md, docs/config-values.rst, pom.xml, src/main/java/com/purbon/kafka/topology/BuilderCLI.java, src/main/java/com/purbon/kafka/topology/ClusterState.java, src/main/java/com/purbon/kafka/topology/KafkaTopologyBuilder.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/java/com/purbon/kafka/topology/api/adminclient/TopologyBuilderAdminClientBuilder.java, src/main/java/com/purbon/kafka/topology/backend/Backend.java, src/main/java/com/purbon/kafka/topology/backend/FileBackend.java, src/main/java/com/purbon/kafka/topology/backend/RedisBackend.java, src/main/java/com/purbon/kafka/topology/model/Impl/ProjectImpl.java, src/main/java/com/purbon/kafka/topology/model/Impl/TopicImpl.java, src/main/resources/reference.conf, src/test/java/com/purbon/kafka/topology/ClusterStateTest.java, src/test/java/com/purbon/kafka/topology/KafkaTopologyBuilderTest.java, src/test/java/com/purbon/kafka/topology/TopicManagerTest.java, src/test/java/com/purbon/kafka/topology/TopologyBuilderConfigTest.java, src/test/java/com/purbon/kafka/topology/TopologyValidationTest.java, src/test/java/com/purbon/kafka/topology/backend/RedisBackendTest.java, src/test/java/com/purbon/kafka/topology/integration/backend/RedisBackendIT.java, src/test/resources/client-config-redis.properties
This Pull Request adds support for:
* the lightbend config library.
This library give support for:
* better default values management.
* support for environment variables as configuration replacements.
* support for json, yaml and hacon files as well as property files for configs.
* made the broker config optional if the config one is specified.
more references at: https://github.com/lightbend/config
closes #88 #82
=> Add a configuration management library

changelog.md, docs/config-values.rst, src/main/conf/topology-builder.properties, src/test/java/com/purbon/kafka/topology/TopologyBuilderConfigTest.java, src/test/resources/config-internals-extended.properties
This pull request added a couple of more test and examples for how to use the kafka internal topic prefix list since the introduction of the lightbend config library.
As a context, the former 
```java
kafka.internal.topic.prefixes="_,topicA,topicB"
```
format will no longer be supported, because this was doing an internal split by ",". Now the expected way of passing a list from the properties file would be by the spec:
```java
kafka.internal.topic.prefixes.0=_
kafka.internal.topic.prefixes.1=topicA
kafka.internal.topic.prefixes.2=topicB
```
pending:
- [ ] add examples for _kafka.internal.topic.prefixes_ and _topology.validations_ under the relevant directory.
closes #113
=> Added test for list of topics as from properties file and examples

docs/the-descriptor-files.rst, example/descriptor.json, pom.xml, src/main/conf/topology-builder.properties, src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/java/com/purbon/kafka/topology/TopologyDescriptorBuilder.java, src/main/java/com/purbon/kafka/topology/serdes/TopologySerdes.java, src/main/resources/reference.conf, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/resources/descriptor.json
This pull request add code to handle other file descriptor formats such as:
*xml* for a future pull request
(*work in progress*, xml needs to redefine the custom parser)
*NOTE*: This future is for the upcoming 2.0 branch
closes #107
=> Enable JSON and YAML as Topology descriptor file formats.

src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/BindingsBuilderProvider.java, src/main/java/com/purbon/kafka/topology/actions/access/builders/BuildBindingsForProducer.java, src/main/java/com/purbon/kafka/topology/model/users/Producer.java, src/main/java/com/purbon/kafka/topology/roles/acls/AclsBindingsBuilder.java, src/main/java/com/purbon/kafka/topology/roles/rbac/RBACBindingsBuilder.java, src/main/java/com/purbon/kafka/topology/serdes/TopologyCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/java/com/purbon/kafka/topology/AclsBindingsBuilderTest.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java, src/test/resources/descriptor.yaml
This PR add ACLs to support Transactional and idempotence producing in KTB. The Consuming part does not need any new ACL as all is setup as expected and required.
close #98
=> Add support for Transactional and Idempotence producing and consuming in KTB

docs/config-values.rst, docs/futures/what-acl-management.rst, src/main/conf/topology-builder.properties, src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/BindingsBuilderProvider.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/java/com/purbon/kafka/topology/actions/access/builders/BuildBindingsForConsumer.java, src/main/java/com/purbon/kafka/topology/actions/access/builders/BuildBindingsForProducer.java, src/main/java/com/purbon/kafka/topology/roles/acls/AclsBindingsBuilder.java, src/main/java/com/purbon/kafka/topology/roles/rbac/RBACBindingsBuilder.java, src/main/resources/reference.conf, src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/java/com/purbon/kafka/topology/AclsBindingsBuilderTest.java, src/test/java/com/purbon/kafka/topology/RbacProviderTest.java, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java
This function is selected via configuration option.
tasks:
closes #80
=> Add an option of grouping ACLs for consumers and producers 

pom.xml, src/test/java/com/purbon/kafka/topology/integration/TopicManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/backend/RedisBackendIT.java
The testcontainers project was recently updated to be able to run on Macs with recent versions of Docker. See https://github.com/testcontainers/testcontainers-java/releases/tag/1.15.0-rc2
This PR upgrades testcontainers to the fixed version.
=> Upgrade testcontainers to support recent Docker for Mac.

pom.xml, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/KafkaTopologyBuilderIT.java, src/test/java/com/purbon/kafka/topology/integration/SaslPlaintextKafkaContainer.java, src/test/java/com/purbon/kafka/topology/integration/TopicManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/containerutils/SaslPlaintextKafkaContainer.java
I saw that one integration test used KafkaContainer, while others assumably rely on a local Kafka to have been started manually. I thought it would be a good idea to be able to run all the integration tests using testcontainers, and I started with rewriting the tests for ACLs.
The SaslPlaintextKafkaContainer is based on the original KafkaContainers, but modified to support 6.0.0 from Confluent, and to run with SASL_PLAINTEXT natively.
I don't know if you want this change, but...
=> ACL integration tests using testcontainers

src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/BackendController.java, src/main/java/com/purbon/kafka/topology/ExecutionPlan.java, src/main/java/com/purbon/kafka/topology/backend/FileBackend.java
Running KTB twice with the same topology will still cause the .cluster-state file to change on every run. Because of usage of HashSet in a number of places the order of ACLs in the file will change on each run. This is undesired and especially a problem if using the FileBackend and wanting to push the file to some repo if changed.
Changed to LinkedHashSet to fix this.
=> Make writing .cluster-state file idempotent

src/deb/control/preinst, src/deb/control/prerm, src/main/scripts/preinstall.sh, src/main/scripts/remove.sh
This PR fix the case when users already exist in the system and when doing the upgrade the script fails with an error so the rpm/deb manager stops the upgrade.
#closes #171
=> Fix RPM/DEB packaging update  

src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/java/com/purbon/kafka/topology/TestTopologyBuilder.java
This fixes #167. Improved the acl delete tests as described and also changed some other tests to use the new test data/topology builder.
=> Improve AccessControlManagerTest

docs/config-values.rst, src/main/java/com/purbon/kafka/topology/BackendController.java, src/main/java/com/purbon/kafka/topology/ExecutionPlan.java, src/main/java/com/purbon/kafka/topology/TopicManager.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/java/com/purbon/kafka/topology/actions/topics/DeleteTopics.java, src/main/java/com/purbon/kafka/topology/actions/topics/SyncTopicAction.java, src/main/java/com/purbon/kafka/topology/backend/Backend.java, src/main/java/com/purbon/kafka/topology/backend/FileBackend.java, src/main/java/com/purbon/kafka/topology/backend/RedisBackend.java, src/main/java/com/purbon/kafka/topology/utils/JSON.java, src/main/java/com/purbon/kafka/topology/utils/StreamUtils.java, src/main/resources/reference.conf, src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/java/com/purbon/kafka/topology/BackendControllerTest.java, src/test/java/com/purbon/kafka/topology/ExecutionPlanTest.java, src/test/java/com/purbon/kafka/topology/TopicManagerTest.java, src/test/java/com/purbon/kafka/topology/TopologyBuilderAdminClientTest.java, src/test/java/com/purbon/kafka/topology/backend/FileBackendTest.java, src/test/java/com/purbon/kafka/topology/integration/RBACPRoviderRbacIT.java, src/test/java/com/purbon/kafka/topology/integration/TopicManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/backend/DefaultBackendIT.java
As of now the KTB retrieve the topic status (what has been created) directly from the cluster. There is an option to filter out what the user does not want to consider, however in a more multi tenant scenario, users want to control only what is managed by each of the KTB instances and the number can be bigger.
We will keep the current behaviour as default till the release of 2.0, however, users would have the option to store the managed topics in the status backends. The use of status backends will be the …
=> Allow topic state bookkeeping from the cluster backend state system  

src/main/scripts/kafka-topology-builder.sh
Simple fix to add an environment variable to the startup script in the docker image. With this the user can pass JVM arguments via environment variables
Right now there is not way to pass arguments to the JVM
With this change the user can just pass an environment variable with all the "-D" arguments required
It should not since if the environment variable is not set it would just behave …
=> Adding ability to pass KTB options for the jvm or the KTB itself via an environment variable

src/main/java/com/purbon/kafka/topology/model/Impl/TopicImpl.java
Whilst it is possible to use a pattern like {{ topic }} when other tooling is being used like ansible there is a collision with {{ }} as it also uses jinja templating.
=> Add ability to use the name as the end topic name

docs/config-values.rst, src/main/java/com/purbon/kafka/topology/TopologyValidator.java, src/main/java/com/purbon/kafka/topology/roles/CCloudAclsProvider.java, src/test/java/com/purbon/kafka/topology/TopologyValidationTest.java
This fixes #201. 
In addition the following improvements have been done:
- Fail on validation class not found in class path. KTB should not preceed with processing in this case.
Feature improvement.
See #201.
See #201.
No. Removing old, now deprecated behavior, should be handled in a later commit.
=> Support topology validations with fully qualified class names as configuration values (backwards compatible)

src/main/java/com/purbon/kafka/topology/backend/FileBackend.java
Hi,
This PR fixes 1 violations of [Sonar Rule 2095: 'Resources should be closed'](https://rules.sonarsource.com/java/RSPEC-2095).
The patch was generated automatically with the tool [Sorald](https://github.com/SpoonLabs/sorald). For details on the fix applied here, please see [Sorald's documentation on rule 2095](https://github.com/SpoonLabs/sorald/blob/master/docs/HANDLED_RULES.md#resources-should-be-closed-sonar-rule-2095).
=> [Sonar 2095] Fix, resources should be closed

.gitignore, docs/config-values.rst, pom.xml, src/main/java/com/purbon/kafka/topology/BackendController.java, src/main/java/com/purbon/kafka/topology/Configuration.java, src/main/java/com/purbon/kafka/topology/Constants.java, src/main/java/com/purbon/kafka/topology/JulieOps.java, src/main/java/com/purbon/kafka/topology/api/mds/MDSApiClient.java, src/main/java/com/purbon/kafka/topology/backend/Backend.java, src/main/java/com/purbon/kafka/topology/backend/BackendState.java, src/main/java/com/purbon/kafka/topology/backend/FileBackend.java, src/main/java/com/purbon/kafka/topology/backend/GCPBackend.java, src/main/java/com/purbon/kafka/topology/backend/RedisBackend.java, src/main/java/com/purbon/kafka/topology/backend/S3Backend.java, src/main/java/com/purbon/kafka/topology/roles/TopologyAclBinding.java, src/test/java/com/purbon/kafka/topology/BackendControllerTest.java, src/test/java/com/purbon/kafka/topology/JulieOpsTest.java, src/test/java/com/purbon/kafka/topology/backend/FileBackendTest.java, src/test/java/com/purbon/kafka/topology/backend/RedisBackendTest.java, src/test/java/com/purbon/kafka/topology/integration/backend/RedisBackendIT.java, src/test/java/com/purbon/kafka/topology/integration/backend/S3BackendIT.java, src/test/java/com/purbon/kafka/topology/utils/TestUtils.java
Done:
* move local file state to use a JSON format based on the backstage class. This will help add and manage new fields in the state when required (this change is not backwards compatible and will only go to 3.x version)
* Add S3 Backend integration
* Add GCP Backend integration
closes #193 #197
=> Backend management refactoring, S3 and GCP Backend integration

src/main/java/com/purbon/kafka/topology/JulieOps.java
…he end) of JulieOps.build
A minor bug mentioned in - https://github.com/kafka-ops/julie/pull/252 - deserves its own separate PR.
Generic topology checks (file exists, determining clientConfig path, etc), should be done before creating a JulieOps builder instead of after.
=> verify CLI parameters as first thing in the process before creating the main handler object

src/main/java/com/purbon/kafka/topology/model/users/Consumer.java, src/main/java/com/purbon/kafka/topology/model/users/Producer.java, src/main/java/com/purbon/kafka/topology/roles/acls/AclsBindingsBuilder.java, src/test/java/com/purbon/kafka/topology/AclsBindingsBuilderTest.java, src/test/java/com/purbon/kafka/topology/TestTopologyBuilder.java, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java
Currently producer transaction id and consumer group are treated as literals.  This PR addresses #270 by allowing a trailing * to denote a resource pattern type prefix
```
consumers:
- principal: "User:greta"
group: "greta*"
```
and
```
producers:
- principal: "User:greta"
transactionId: "greta*"
```
Since this is not changing the structure then there should not be any braking changes.  Have added test cases.
=> #270 support prefix for producer transaction id and consumer group

src/main/java/com/purbon/kafka/topology/model/cluster/ServiceAccount.java
- [ x] The commit messages are descriptive
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)
- [x ] An issue has been created for the pull requests. Some issues might require previous discussion.
Bug fix:
Added resource_id property to ServiceAccount to remove JSON error.
See https://github.com/kafka-ops/julie/issues/307  
When attempting to manage Confluent Cloud service accounts with the JulieOps CLI tool while using any version of ccloud above v1.27.0, the error message:
``` …
```
=> Fix: Unrecognized field "resource_id" (#307)

.github/workflows/nightly-artifacts-build.yml, .github/workflows/release-artifacts-build.yml, docs/how-to-run-it.rst
Fixes #303
Feature
Deb and Rpms are not signed
Deb and Rpms are signed
In order to get it running we need the following repo secrets:
`GPG_PRIVATE_KEY` -> the armored export of the private gpg key
as described here: https://github.com/marketplace/actions/import-gpg
`GPG_PASSPHRASE` -> the pass phrase for the private pgp key
Furthermore we need in `release/keys/public.key` the matching public part - also armored exported
=> Sign rpm and deb packages after building

docs/futures/what-acl-management.rst
**DOCS UPDATE**
`transactionId` can be specified both with literal value and pattern syntax (as introduced in https://github.com/kafka-ops/julie/pull/279), this was not clear from previous documentation nor examples. I intentionally used the words 'transaction**al** ID' when describing it, because that is what the Kafka documentation uses (in addition to calling the variable `transactional.id`), to make it more searchable.
I tried to find the right section for this, did I find the right place?
~~As far as I know, `transactionId` is also a property for streams, should it be mentioned in that section as well?~~ It is not, as far as I could see.
This feature (prefix syntax) is not in the current release (2.1.2, which is from april). If this goes into documentation, maybe it should be part of …
=> docs: add producer example with transactionID

docs/config-values.rst, src/main/java/com/purbon/kafka/topology/Configuration.java, src/main/java/com/purbon/kafka/topology/Constants.java, src/main/java/com/purbon/kafka/topology/JulieOps.java, src/main/java/com/purbon/kafka/topology/api/connect/KConnectApiClient.java, src/main/java/com/purbon/kafka/topology/api/mds/MDSApiClient.java, src/main/java/com/purbon/kafka/topology/api/mds/MDSApiClientBuilder.java, src/main/java/com/purbon/kafka/topology/clients/JulieHttpClient.java, src/test/java/com/purbon/kafka/topology/integration/ConnectApiClientIT.java, src/test/java/com/purbon/kafka/topology/integration/ConnectorManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/containerutils/ConnectContainer.java
Enable the use of custom trusstore and keystore with the base julie http client, so it is not necessary to pass global jvm level stores anymore.
As a user if you pass:
* ssl.keystore.location
* ssl.keystore.password
* ssl.truststore.location
* ssl.truststore.password
* ssl.key.password
note, same as with kafka, this would be used as well when talking with anything Julie uses via a custom HTTP client. This is for now connector API and MDS server. 
As well important, until this change, you need to pass global JVM keystore configuration properties in order to achieve this, something like https://docs.oracle.com/cd/E29585_01/PlatformServices.61x/security/src/csec_ssl_jsp_start_server.html
* **Does this PR introduce a breaking change?** …
=> Enable the option to pass custom truststore and keystore with custom http clients

docker/sasl/docker-compose.yml, docker/sasl/kafka-connect/Dockerfile, docker/sasl/kafka/kafka.properties, example/connectors/sink-jdbc.json, example/connectors/source-jdbc.json, example/descriptor-connect.yaml, example/topology-builder-sasl-plain.properties, src/main/java/com/purbon/kafka/topology/api/connect/KConnectApiClient.java, src/main/java/com/purbon/kafka/topology/model/Artefact.java
mostly example code and a single extension as toString method.
=> Add connector management to the sasl example

src/main/java/com/purbon/kafka/topology/api/mds/MDSApiClient.java, src/main/java/com/purbon/kafka/topology/api/mds/MDSRequest.java, src/main/java/com/purbon/kafka/topology/roles/rbac/RBACBindingsBuilder.java, src/main/java/com/purbon/kafka/topology/roles/rbac/RBACPredefinedRoles.java, src/test/java/com/purbon/kafka/topology/api/mds/MDSApiClientTest.java
Fix #285 
Subject level binding uses Cluster level binding currently (which is incorrect) and cluster level binding with resources does not use the correct API endpoint.
Therefore an error is returned.
Subject level binding now use subject level binding and cluster level binding uses the correct API endpoint.
No
**IMPORTANT**: Please review the CONTRIBUTING.md …
=> Fix: RBAC Subject and Cluster level binding

pom.xml, src/main/java/com/purbon/kafka/topology/model/users/platform/SchemaRegistryInstance.java, src/main/java/com/purbon/kafka/topology/roles/acls/AclsBindingsBuilder.java, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java
Bug fix: Add missing Schema Registry ACLs (#296)
Adds field consumer_offsets_topic under platform schema_registry instances. 
```
platform:
schema_registry:
instances:
- principal: "User:schema_registry"
topic: "foo"
consumer_offsets_topic: "foo_offsets"  # new field
group: "bar"
```
Change is now done so that it won't break anything but introduces new fields and additional ACLs that are required for schema-registry principal.
topic field is not that descriptive. Should be something like …
=> Add missing Schema Registry ACLs

docker/sasl/docker-compose.yml, docker/sasl/kafka-connect/Dockerfile, docker/sasl/kafka-connect/connect.jaas, docker/sasl/kafka-connect/connect.password, example/topology-builder-sasl-plain.properties, src/main/java/com/purbon/kafka/topology/Configuration.java, src/main/java/com/purbon/kafka/topology/Constants.java, src/main/java/com/purbon/kafka/topology/JulieOps.java, src/main/java/com/purbon/kafka/topology/api/connect/KConnectApiClient.java, src/main/java/com/purbon/kafka/topology/api/mds/MDSApiClient.java, src/main/java/com/purbon/kafka/topology/api/mds/MDSApiClientBuilder.java, src/main/java/com/purbon/kafka/topology/backend/RedisBackend.java, src/main/java/com/purbon/kafka/topology/clients/JulieHttpClient.java, src/main/java/com/purbon/kafka/topology/roles/rbac/RBACPredefinedRoles.java, src/main/resources/reference.conf, src/test/java/com/purbon/kafka/topology/integration/ConnectApiClientIT.java, src/test/java/com/purbon/kafka/topology/integration/backend/RedisBackendIT.java, src/test/java/com/purbon/kafka/topology/integration/containerutils/ConnectContainer.java
=> Configure basic auch for Kafka Connect REST api operations

src/main/java/com/purbon/kafka/topology/serdes/TopologyCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/resources/descriptor-streams-only-read.yaml, src/test/resources/descriptor-streams-only-write.yaml
Might provide closure for #364, pending discussion 
close #364
=> Relax the conditions for kstream application to not require read and write topics all the topic. included as well more easy to catch error messages

src/main/resources/reference.conf
Add env vars for configuring kafka.config.topic (JULIE_KAFKA_CONFIG_TOPIC) and instance.id (JULIE_INSTANCE_ID), all vars used within the context of the kafka backend.
=> Add env vars for kafka.config.topic and instance.id

src/main/java/com/purbon/kafka/topology/serdes/TopologyCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/java/com/purbon/kafka/topology/integration/backend/KafkaBackendIT.java
Now you can use compatible java regexp as a way to select or deny topics to be used within the DLQ future scope.
=> Enable the use of patterns within the DLQ allow and deny list

src/main/java/com/purbon/kafka/topology/BindingsBuilderProvider.java, src/main/java/com/purbon/kafka/topology/actions/access/builders/BuildBindingsForKStreams.java, src/main/java/com/purbon/kafka/topology/model/users/KStream.java, src/main/java/com/purbon/kafka/topology/roles/acls/AclsBindingsBuilder.java, src/main/java/com/purbon/kafka/topology/roles/rbac/RBACBindingsBuilder.java, src/main/java/com/purbon/kafka/topology/serdes/TopologyCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/java/com/purbon/kafka/topology/AclsBindingsBuilderTest.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/java/com/purbon/kafka/topology/actions/access/builders/BuildBindingsForKStreamsTest.java
Fix #387
Feature #387 
Backward compatible. Flag is disable by default.
=> feat: add exactly-once to kstreams and create transactionalid ACLs

src/main/java/com/purbon/kafka/topology/roles/rbac/ClusterLevelRoleBuilder.java, src/test/java/com/purbon/kafka/topology/api/mds/MDSApiClientTest.java
Fix incorrect Confluent RBAC resource name for subjects and connectors.
close #402 #399 #375 #286
=> fix: incorrect rbac resource name for subjects and connectors

docs/futures/use-of-custom-config-plans.rst, src/main/java/com/purbon/kafka/topology/serdes/TopicCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/TopologyObjectBuilderTest.java
This PR fix issue #409 
Configuration values are now updated with plan values only if they do not already exist.
=> Fix: Topic config values should take precedence over plan config values

src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/api/mds/MDSApiClient.java, src/test/java/com/purbon/kafka/topology/integration/RBACPRoviderRbacIT.java
=> fix/feature: make service accounts prefix filter a primary criteria when available to filter the list of access control rules

src/main/java/com/purbon/kafka/topology/serdes/TopicCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/TopologyObjectBuilderTest.java, src/test/resources/descriptor-with-invalid-plan.yaml
We have had a couple of incidents where people have misspelled the plan name. JulieOps logs a warning about this and falls back to default configuration. Nobody sees the warning, so the result is incorrectly configured topics that nobody notices before it is too late.
I think it makes no sense to let people specify a plan that does not exist, so this PR will change the warning to an exception.
=> Throw exception for invalid plan name

src/main/java/com/purbon/kafka/topology/backend/RedisBackend.java, src/test/java/com/purbon/kafka/topology/integration/backend/RedisBackendIT.java
* **What kind of change does this PR introduce?** Bug fix
Fix case when first load happends from redis and no state is there, null return handling, added related test as well
broken see #453 
close #453
=> Fix RedisBackend bootstrap, NullPointerException

src/main/java/com/purbon/kafka/topology/TopologyValidator.java, src/main/java/com/purbon/kafka/topology/validation/topic/ConfigurationKeyValidation.java, src/main/java/com/purbon/kafka/topology/validation/topic/PartitionNumberValidation.java, src/main/java/com/purbon/kafka/topology/validation/topic/ReplicationFactorValidation.java, src/main/java/com/purbon/kafka/topology/validation/topology/CamelCaseNameFormatValidation.java
- [x ] The commit messages are descriptive
Revert backwards compatibility break introduced in https://github.com/kafka-ops/julie/pull/443
Validators with just no-arg constructors fail to load.
Validators with just no-arg constructors will load again, if no Configuration constructor is found.
Hopefully not.
=> Add validators backwards compatibility

src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/ArtefactManager.java, src/main/java/com/purbon/kafka/topology/KSqlArtefactManager.java, src/main/java/com/purbon/kafka/topology/KafkaConnectArtefactManager.java, src/main/java/com/purbon/kafka/topology/TopicManager.java, src/main/java/com/purbon/kafka/topology/exceptions/RemoteValidationException.java, src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/java/com/purbon/kafka/topology/ArtefactManagerTest.java, src/test/java/com/purbon/kafka/topology/TopicManagerTest.java, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/ConnectorManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/KsqlManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/TopicManagerIT.java
This PR introduced a new feature to detect changes between the local state and the remote cluster status. For this first version, JulieOps is going to raise an exception and 🤯  until the divergence is fixed either by updating the local state or fixing the remote cluster. *Note*, in future versions this behaviour will be expected with more granular support.
Managers supported:
**Note**: Changing resources outside the scope of JulieOps it is not a good practice, but this PR will help teams detect such cases in case they happen.
=> Detect divergences between local state and the remote cluster current status

src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/ArtefactManager.java, src/main/java/com/purbon/kafka/topology/Configuration.java, src/main/java/com/purbon/kafka/topology/Constants.java, src/main/java/com/purbon/kafka/topology/TopicManager.java, src/main/resources/reference.conf, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/ConnectorManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/KsqlManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/TopicManagerIT.java
to be removed in future versions and make true by default.
=> Add feature flag to make the remote state verification backwards compatible again

src/main/java/com/purbon/kafka/topology/ExecutionPlan.java, src/main/java/com/purbon/kafka/topology/validation/topic/MinInSyncReplicasValidation.java, src/test/java/com/purbon/kafka/topology/TopicManagerTest.java, src/test/java/com/purbon/kafka/topology/validation/topic/MinInSyncReplicasValidationTest.java
- [* ] The commit messages are descriptive
Fix for https://github.com/kafka-ops/julie/issues/510
I only changed `ExecutionPlan.java` and `TopicManagerTest.java`. The other two files were changed due to the embedded formatter.
=> Don't print empty operations

src/main/java/com/purbon/kafka/topology/model/Impl/ProjectImpl.java, src/main/java/com/purbon/kafka/topology/model/Topic.java, src/main/java/com/purbon/kafka/topology/validation/topic/MinInSyncReplicasValidation.java, src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/java/com/purbon/kafka/topology/ConfigurationTest.java, src/test/java/com/purbon/kafka/topology/TopologyObjectBuilderTest.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/java/com/purbon/kafka/topology/actions/topics/CreateTopicActionTest.java, src/test/java/com/purbon/kafka/topology/actions/topics/DeleteTopicsActionTest.java, src/test/java/com/purbon/kafka/topology/validation/topic/MinInSyncReplicasValidationTest.java
=> extend the project name format to include by default the separator, this is useful to narrow down optimized acls to be more secure

src/main/java/com/purbon/kafka/topology/Configuration.java, src/test/java/com/purbon/kafka/topology/ConfigurationTest.java
=> Add a config test to validate when people use empty managed prefixes as mistake

docs/config-values.rst, src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/Configuration.java, src/main/java/com/purbon/kafka/topology/Constants.java, src/main/java/com/purbon/kafka/topology/roles/ResourceFilter.java, src/main/resources/reference.conf, src/test/java/com/purbon/kafka/topology/ConfigurationTest.java, src/test/java/com/purbon/kafka/topology/ResourceFilterTest.java, src/test/java/com/purbon/kafka/topology/integration/RBACPRoviderRbacIT.java
This PR introduce the support of subject prefix filtering.
Currently it is not possible to define which subjects should be managed.
As we can do with topics and groups, with this PR, we can now manage which subjects should be managed using prefixes.
No
Fix #526.
=> Add Subject prefix filtering support

.gitignore, pom.xml, src/main/resources/log4j.properties, src/main/resources/log4j2.yml, src/test/resources/log4j2.yml
This change introduces project structure cleanup and some dependency refreshing.
Changes:
* Jackson dependencies imported via BOM to avoid multiple versioned declarations
* Logging switched to Log4j2 from outdated libraries
* Javadoc plugin moved before shade plugin to enable Java 11 compatibility (declared by compiler plugin); the plugin spammed build log with warnings about **var** keyword unsupported in Java 8.
=> Housekeeping changes

.github/dependabot.yml
Ref [failing Dependabot actions](https://github.com/kafka-ops/julie/runs/16721025360).
=> ci: Lower-case maven for Dependabot (fixes nightly)

.github/workflows/nightly-artifacts-build.yml, .github/workflows/release-artifacts-build.yml
Ref [failing Maven builds](https://github.com/kafka-ops/julie/actions/runs/6161550014/job/16721027019).
`mvn deploy` also includes `verify`. By giving both `verify` and `deploy`, the newer version of `maven-source-plugin` complains.
=> ci: Give just one lifecycle phase to maven (fixes nightly)

docker/rbac-sasl/create-roles.sh, docker/rbac-sasl/docker-compose.yml, docs/handling-delete.rst, src/main/java/com/purbon/kafka/topology/Configuration.java, src/main/java/com/purbon/kafka/topology/Constants.java, src/main/java/com/purbon/kafka/topology/JulieOps.java, src/main/java/com/purbon/kafka/topology/actions/quotas/CreateQuotasAction.java, src/main/java/com/purbon/kafka/topology/actions/quotas/DeleteQuotasAction.java, src/main/java/com/purbon/kafka/topology/api/adminclient/TopologyBuilderAdminClient.java, src/main/java/com/purbon/kafka/topology/model/users/platform/Kafka.java, src/main/java/com/purbon/kafka/topology/quotas/QuotasManager.java, src/main/resources/reference.conf, src/test/java/com/purbon/kafka/topology/JulieOpsTest.java, src/test/java/com/purbon/kafka/topology/integration/QuotasManagerIT.java
This fixes the integration and support of quotas in Julie Ops, including current state and deletion.
It does not work at all because the quota manager is not plugged and the data model does not contain quota declaration.
Quotas are supported for creation, current state and deletion with as usual a flag to allow deletion.
No prefix management has been implemented because quotas are only using Users and therefore quotas should be declared in only one unique file. 
* **Does this PR introduce a breaking change?** …
=> Fix quota manager integration

src/test/java/com/purbon/kafka/topology/JulieOpsTest.java
…port
This PR fixes the CLI integration tests, broken since the quotas fix #581.
Timeout during integration tests.
Tests should pass now.
No.
**IMPORTANT**: Please review the CONTRIBUTING.md file for detailed contributing guidelines.
**IMPORTANT**: Your pull request MUST target `master`.
PLEASE REMOVE THIS TEMPLATE BEFORE SUBMITTING
=> Fix: CLI integration tests do not use correct credentials and broker port

.github/workflows/ci-integration-test-legacy.yml, .github/workflows/ci-integration-test-main.yml, .github/workflows/ci-unit-test-legacy.yml, .github/workflows/ci-unit-test-main.yml, .github/workflows/nightly-artifacts-build.yml, .github/workflows/release-artifacts-build-legacy.yml, .github/workflows/release-artifacts-build.yml, .github/workflows/release-docker-legacy.yml, .github/workflows/release-docker.yml, pom.xml, src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/ArtefactManager.java, src/main/java/com/purbon/kafka/topology/CommandLineInterface.java, src/main/java/com/purbon/kafka/topology/Configuration.java, src/main/java/com/purbon/kafka/topology/Constants.java, src/main/java/com/purbon/kafka/topology/OnceOnlyWarningLogger.java, src/main/java/com/purbon/kafka/topology/TopicManager.java, src/main/java/com/purbon/kafka/topology/clients/JulieHttpClient.java, src/main/java/com/purbon/kafka/topology/serdes/TopologyCustomDeserializer.java, src/main/java/com/purbon/kafka/topology/utils/JSON.java, src/main/resources/reference.conf, src/test/java/com/purbon/kafka/topology/CLITest.java, src/test/java/com/purbon/kafka/topology/ConfigurationTest.java, src/test/java/com/purbon/kafka/topology/integration/backend/RedisBackendIT.java, src/test/java/com/purbon/kafka/topology/integration/containerutils/ConnectContainer.java, src/test/java/com/purbon/kafka/topology/integration/containerutils/ContainerTestUtils.java, src/test/java/com/purbon/kafka/topology/integration/containerutils/SchemaRegistryContainer.java
This is a "While you were gone, take 2".
* Updates certain GitHub actions to get rid of a lot of warnings.
* Updates most dependencies to the most recent version.
* When pretty-printing JSON, split arrays in one entry per line. This makes it much easier to spot differences in `.cluster-state`.
* Display the warning for disabled remote state verification just once.
* Make it possible to disable warnings printed when projects contain no topics.
* Make it possible to disable warnings printed when streams have no writers.
~~This PR is one commit behind `master`, since [the most recently merged contribution](https://github.com/kafka-ops/julie/pull/581) breaks [the unit tests](https://github.com/kafka-ops/julie/actions/runs/7743200322/job/21114078917#step:5:1176). (Maybe revert it to have unit …
=> chore: misc updates and improvements made while you were gone, take 2
