kafka-ops/julie

.gitignore, changelog.md, example/descriptor.yaml, kafka-topology-builder.iml, pom.xml, src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/AccessControlProvider.java, src/main/java/com/purbon/kafka/topology/ClusterState.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderAdminClient.java, src/main/java/com/purbon/kafka/topology/api/mds/MDSApiClient.java, src/main/java/com/purbon/kafka/topology/clusterstate/FileSateProcessor.java, src/main/java/com/purbon/kafka/topology/clusterstate/StateProcessor.java, src/main/java/com/purbon/kafka/topology/roles/RBACProvider.java, src/main/java/com/purbon/kafka/topology/roles/SimpleAclsProvider.java, src/main/java/com/purbon/kafka/topology/roles/TopologyAclBinding.java, src/main/java/com/purbon/kafka/topology/utils/ZKClient.java, src/main/java/com/purbon/kafka/topology/utils/ZKConnection.java, src/main/resources/log4j2.yml, src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/MDSApiClientRbacIT.java, src/test/java/com/purbon/kafka/topology/integration/MDSBaseTest.java, src/test/java/com/purbon/kafka/topology/integration/RBACPRoviderRbacIT.java
v0.11:
* Add support for storing the current generated acls within a state file. This is useful to delete
acls that are known and generated previously by the topology builder.
=> Add support to keeping notes of generated acls

src/main/java/com/purbon/kafka/topology/AccessControlProvider.java, src/main/java/com/purbon/kafka/topology/api/mds/MDSApiClient.java, src/main/java/com/purbon/kafka/topology/api/mds/RequestScope.java, src/main/java/com/purbon/kafka/topology/api/mds/http/HttpDeleteWithBody.java, src/main/java/com/purbon/kafka/topology/roles/AdminRoleRunner.java, src/main/java/com/purbon/kafka/topology/roles/RBACProvider.java, src/main/java/com/purbon/kafka/topology/roles/TopologyAclBinding.java, src/test/java/com/purbon/kafka/topology/AccessControlWithRBACTest.java, src/test/java/com/purbon/kafka/topology/integration/RBACPRoviderRbacIT.java
This PR implements the necessary methods in the RBAC support to provide back as well there the necessary operations to sync roles dynamically.
fixes #29
=> [WiP] Implement status sync for roles in the RBAC provided

changelog.md, docs/config-values.rst, docs/index.rst, pom.xml, src/main/java/com/purbon/kafka/topology/KafkaTopologyBuilder.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/java/com/purbon/kafka/topology/clusterstate/RedisSateProcessor.java, src/test/java/com/purbon/kafka/topology/integration/clusterstate/RedisStateProcessorIT.java
Option to add an external status keeper in redis.
fixes #24
=> Option to add an external status keeper (backed by redis)

changelog.md, example/topology-builder-rbac.properties, pom.xml, scripts/run-rbac-with-docker.sh, src/main/java/com/purbon/kafka/topology/BuilderCLI.java, src/main/java/com/purbon/kafka/topology/KafkaTopologyBuilder.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/java/com/purbon/kafka/topology/roles/RBACProvider.java, src/test/java/com/purbon/kafka/topology/KafkaTopologyBuilderTest.java
This PR corrects a few issues found during testing of the RBAC execution flow. 
closes #36
=> Fix various errors regarding the RBACProvider flow

docker/rbac-sasl/docker-compose.yml, example/topology-builder-rbac.properties, src/test/java/com/purbon/kafka/topology/KafkaTopologyBuilderTest.java
=> RBAC Authentication -> LDAP

changelog.md, docs/what-can-you-do.rst, src/main/java/com/purbon/kafka/topology/TopicManager.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderAdminClient.java, src/main/java/com/purbon/kafka/topology/model/Impl/TopicImpl.java, src/main/java/com/purbon/kafka/topology/model/Topic.java, src/test/java/com/purbon/kafka/topology/TopicManagerTest.java
This pull request implements a simple method to allow the increase of partitions count without passing a determinate partition placement.
solved #55
=> Add an option to increase partition count

src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/AccessControlProviderFactory.java, src/main/java/com/purbon/kafka/topology/KafkaTopologyBuilder.java, src/main/java/com/purbon/kafka/topology/TopicManager.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/test/java/com/purbon/kafka/topology/KafkaTopologyBuilderTest.java, src/test/java/com/purbon/kafka/topology/TopicManagerTest.java, src/test/java/com/purbon/kafka/topology/TopologyBuilderConfigTest.java
Refactored access to config values by added a bunch of getters to TopologyBuilderConfig.
=> Add allow deletes config

changelog.md, src/main/java/com/purbon/kafka/topology/api/adminclient/TopologyBuilderAdminClient.java
=> add a filter to remove only configs that have been explicitly set

changelog.md, notes.md, src/main/java/com/purbon/kafka/topology/api/adminclient/TopologyBuilderAdminClient.java, src/main/java/com/purbon/kafka/topology/api/adminclient/TopologyBuilderAdminClientBuilder.java, src/test/java/com/purbon/kafka/topology/KafkaTopologyBuilderTest.java, src/test/java/com/purbon/kafka/topology/integration/KafkaTopologyBuilderIT.java, src/test/resources/wrong-client-config.properties
=> Add a basic Healthcheck function while building the internal Admin client

src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/BackendController.java, src/main/java/com/purbon/kafka/topology/ExecutionPlan.java, src/main/java/com/purbon/kafka/topology/backend/Backend.java, src/main/java/com/purbon/kafka/topology/backend/FileBackend.java, src/main/java/com/purbon/kafka/topology/backend/RedisBackend.java, src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/java/com/purbon/kafka/topology/ExecutionPlanTest.java, src/test/java/com/purbon/kafka/topology/KafkaTopologyBuilderTest.java, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java
fixes important error reported at #125
=> Fix ACL removal bug

src/main/java/com/purbon/kafka/topology/actions/topics/SyncTopicAction.java, src/main/java/com/purbon/kafka/topology/model/Impl/TopicImpl.java, src/main/java/com/purbon/kafka/topology/model/TopicSchemas.java, src/main/java/com/purbon/kafka/topology/serdes/TopicCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/resources/descriptor-wrong-schemas.yaml, src/test/resources/descriptor.yaml
*NOTE*:  Throw an exception if the key schema is present but not value one.
closes #122
=> Make usage of topic key schemas optional, values are always required

docs/futures/use-of-custom-config-plans.rst, example/descriptor-with-plans.yaml, example/plans.yaml, src/main/java/com/purbon/kafka/topology/BuilderCLI.java, src/main/java/com/purbon/kafka/topology/KafkaTopologyBuilder.java, src/main/java/com/purbon/kafka/topology/TopologyDescriptorBuilder.java, src/main/java/com/purbon/kafka/topology/TopologyObjectBuilder.java, src/main/java/com/purbon/kafka/topology/model/Impl/TopicImpl.java, src/main/java/com/purbon/kafka/topology/model/Plan.java, src/main/java/com/purbon/kafka/topology/model/PlanMap.java, src/main/java/com/purbon/kafka/topology/model/Topic.java, src/main/java/com/purbon/kafka/topology/serdes/PlanMapSerdes.java, src/main/java/com/purbon/kafka/topology/serdes/TopicCustomDeserializer.java, src/main/java/com/purbon/kafka/topology/serdes/TopologySerdes.java, src/test/java/com/purbon/kafka/topology/CLITest.java, src/test/java/com/purbon/kafka/topology/ExecutionPlanTest.java, src/test/java/com/purbon/kafka/topology/KafkaTopologyBuilderTest.java, src/test/java/com/purbon/kafka/topology/PlanMapSerdesTest.java, src/test/java/com/purbon/kafka/topology/TopologyObjectBuilderTest.java, src/test/resources/descriptor-with-plans.yaml, src/test/resources/descriptor.yaml, src/test/resources/plans.yaml
=> Add custom plans to help standardise topic config

docs/config-values.rst, docs/futures/what-schema-management.rst, example/topology-builder-rbac-schemas.properties
=> Add schema.registry.url to docs and examples

pom.xml
=> Fix path of topology builder gen jar in the deb package mapping

src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/java/com/purbon/kafka/topology/actions/topics/SyncTopicAction.java, src/main/java/com/purbon/kafka/topology/model/Impl/TopicImpl.java, src/main/java/com/purbon/kafka/topology/model/Topic.java, src/main/java/com/purbon/kafka/topology/serdes/TopicCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/TopologyBuilderConfigTest.java
=> Fix bug with a topology/config not using schemas

README.md, docs/futures/what-acl-management.rst, example/descriptor.yaml, src/main/java/com/purbon/kafka/topology/actions/access/builders/BuildBindingsForKStreams.java, src/main/java/com/purbon/kafka/topology/model/users/KStream.java, src/main/java/com/purbon/kafka/topology/roles/acls/AclsBindingsBuilder.java, src/test/java/com/purbon/kafka/topology/AclsBindingsBuilderTest.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/java/com/purbon/kafka/topology/TopologyValidationTest.java, src/test/java/com/purbon/kafka/topology/actions/access/builders/BuildBindingsForKStreamsTest.java, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java, src/test/resources/descriptor.yaml
This will fix #116.
In addition improved the acl documentation for consumers and producers.
=> Add streams acls for consumer group and support for applicationId

src/main/java/com/purbon/kafka/topology/backend/FileBackend.java, src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/java/com/purbon/kafka/topology/AccessControlWithRBACTest.java, src/test/java/com/purbon/kafka/topology/ClusterLevelRoleBuilderTest.java, src/test/java/com/purbon/kafka/topology/ExecutionPlanTest.java, src/test/java/com/purbon/kafka/topology/KafkaTopologyBuilderTest.java, src/test/java/com/purbon/kafka/topology/PlanMapSerdesTest.java, src/test/java/com/purbon/kafka/topology/RbacProviderTest.java, src/test/java/com/purbon/kafka/topology/TopologyBuilderConfigTest.java, src/test/java/com/purbon/kafka/topology/TopologyObjectBuilderTest.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/java/com/purbon/kafka/topology/TopologyValidationTest.java, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/KafkaTopologyBuilderIT.java, src/test/java/com/purbon/kafka/topology/schemas/SchemaRegistryManagerTest.java, src/test/java/com/purbon/kafka/topology/utils/TestUtils.java
I intend to add some integration tests, but before doing that I have extracted some duplicate code into a TestUtils class.
=> Test cleanup

src/main/java/com/purbon/kafka/topology/TopologyObjectBuilder.java, src/main/java/com/purbon/kafka/topology/exceptions/TopologyParsingException.java, src/main/java/com/purbon/kafka/topology/serdes/TopologySerdes.java, src/test/java/com/purbon/kafka/topology/KafkaTopologyBuilderTest.java, src/test/java/com/purbon/kafka/topology/TopologyObjectBuilderTest.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/resources/errors_dir/descriptor-with-errors.yaml, src/test/resources/errors_dir/descriptor.yaml
=> Fail on parsing of invalid topologies

src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/AclProducerAndConsumerIT.java, src/test/java/com/purbon/kafka/topology/integration/TopicManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/containerutils/AlternativeKafkaContainer.java, src/test/java/com/purbon/kafka/topology/integration/containerutils/ContainerTestUtils.java, src/test/java/com/purbon/kafka/topology/integration/containerutils/SaslPlaintextKafkaContainer.java, src/test/java/com/purbon/kafka/topology/integration/containerutils/TestConsumer.java, src/test/java/com/purbon/kafka/topology/integration/containerutils/TestProducer.java, src/test/resources/acl-producer-and-consumer-it.properties, src/test/resources/acl-producer-and-consumer-it.yaml
Verifying that the populated ACL mappings are sufficient to allow the intended operations for producers and consumers.
=> Integration test verifying that producers can produce and consumers can consume

.github/workflows/docker.yml
This action will push master branch as a latest image in docker hub regularly on push to master and as well daily.
=> Fix action to push master to docker hub as latest

.github/workflows/stale.yml, docs/handling-delete-in-ktb.rst, docs/how-to-run-it.rst, docs/index.rst, src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/BuilderCLI.java, src/main/java/com/purbon/kafka/topology/TopicManager.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/resources/reference.conf, src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/java/com/purbon/kafka/topology/TopicManagerTest.java, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/RBACPRoviderRbacIT.java, src/test/java/com/purbon/kafka/topology/integration/TopicManagerIT.java
=> Allow granular delete flags as well as ENV override 

docs/config-values.rst, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/java/com/purbon/kafka/topology/model/DynamicUser.java, src/main/java/com/purbon/kafka/topology/roles/acls/AclsBindingsBuilder.java, src/main/resources/reference.conf, src/test/java/com/purbon/kafka/topology/AclsBindingsBuilderTest.java
=> Option to disable creation of the CLUSTER CREATE ACL for connectors

src/main/java/com/purbon/kafka/topology/PrincipalManager.java, src/test/java/com/purbon/kafka/topology/PrincipalManagerTest.java
…onsumers/producers at topic levels
=> Fix principle manager not adding principles defined within topics

docs/futures/what-schema-management.rst, example/descriptor-with-schemas.yaml, example/schemas/foo-value.avsc, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/java/com/purbon/kafka/topology/actions/topics/SyncTopicAction.java, src/main/java/com/purbon/kafka/topology/model/Impl/TopicImpl.java, src/main/java/com/purbon/kafka/topology/model/SubjectNameStrategy.java, src/main/java/com/purbon/kafka/topology/model/Topic.java, src/main/java/com/purbon/kafka/topology/model/TopicSchemas.java, src/main/java/com/purbon/kafka/topology/model/schema/Subject.java, src/main/java/com/purbon/kafka/topology/serdes/TopicCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/TopologyBuilderConfigTest.java, src/test/java/com/purbon/kafka/topology/TopologyObjectBuilderTest.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/resources/descriptor.yaml
takes over from #158 
closes #155
=> Support multiple schema per topic

docs/futures/what-schema-management.rst, src/main/java/com/purbon/kafka/topology/PrincipalManager.java, src/main/java/com/purbon/kafka/topology/actions/topics/SyncTopicAction.java, src/main/java/com/purbon/kafka/topology/model/TopicSchemas.java, src/main/java/com/purbon/kafka/topology/model/schema/Subject.java, src/main/java/com/purbon/kafka/topology/model/schemas/Subject.java, src/main/java/com/purbon/kafka/topology/schemas/SchemaRegistryManager.java, src/main/java/com/purbon/kafka/topology/serdes/TopicCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/PrincipalManagerTest.java, src/test/java/com/purbon/kafka/topology/schemas/SchemaRegistryManagerTest.java, src/test/resources/descriptor.yaml
would be great to merge this after #158 
closes #157   #159
=> Add support for custom SchemaTypes and Compatibility level when managing schemas

docs/futures/what-schema-management.rst, src/main/java/com/purbon/kafka/topology/schemas/SchemaRegistryManager.java, src/test/java/com/purbon/kafka/topology/schemas/SchemaRegistryManagerTest.java
=> Add support for absolute paths when fetching schemas from disk

src/main/java/com/purbon/kafka/topology/PrincipalManager.java, src/main/java/com/purbon/kafka/topology/PrincipalProvider.java, src/main/java/com/purbon/kafka/topology/serviceAccounts/CCloudPrincipalProvider.java, src/main/java/com/purbon/kafka/topology/serviceAccounts/VoidPrincipalProvider.java, src/test/java/com/purbon/kafka/topology/PrincipalManagerTest.java
=> [Principal Manager] Enable  state fetching from the cluster for the principals

docs/config-values.rst, docs/futures/what-principal-management.rst, src/main/java/com/purbon/kafka/topology/PrincipalManager.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/resources/reference.conf, src/test/java/com/purbon/kafka/topology/PrincipalManagerTest.java
=> Add support for a prefix list to filter which principals are allowed to be managed

src/main/java/com/purbon/kafka/topology/ExecutionPlan.java, src/main/java/com/purbon/kafka/topology/PrincipalManager.java, src/main/java/com/purbon/kafka/topology/api/ccloud/CCloudCLI.java
=> [PrincipalManager] Improved error handling when using Confluent Cloud 

.github/workflows/ci-integration-test.yml, .github/workflows/maven.yml, pom.xml, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/AclProducerAndConsumerIT.java, src/test/java/com/purbon/kafka/topology/integration/KafkaTopologyBuilderIT.java, src/test/java/com/purbon/kafka/topology/integration/StreamsAclIT.java, src/test/java/com/purbon/kafka/topology/integration/TopicManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/containerutils/ContainerFactory.java
=>  Enable to run integration test parametrised vs multiple cp versions

docs/config-values.rst, docs/futures/what-acl-management.rst, docs/futures/what-principal-management.rst, docs/futures/what-topic-management.rst, src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/AccessControlProviderFactory.java, src/main/java/com/purbon/kafka/topology/KafkaTopologyBuilder.java, src/main/java/com/purbon/kafka/topology/PrincipalManager.java, src/main/java/com/purbon/kafka/topology/TopicManager.java, src/main/java/com/purbon/kafka/topology/TopologyBuilderConfig.java, src/main/java/com/purbon/kafka/topology/model/Impl/TopicImpl.java, src/main/java/com/purbon/kafka/topology/roles/CCloudAclsProvider.java, src/main/java/com/purbon/kafka/topology/serviceAccounts/VoidPrincipalProvider.java, src/main/resources/reference.conf, src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/java/com/purbon/kafka/topology/PrincipalManagerTest.java, src/test/java/com/purbon/kafka/topology/TestTopologyBuilder.java, src/test/java/com/purbon/kafka/topology/TopicManagerTest.java
@purbon ok so found an issue, in that we are leaving ACL's around when running as remote state isnt used. Applied similar approach as TopicManager.
As well added matcher like for principle on topics, so it all works.
Need to add test cases, but raising this PR now for your visibility.
=> Support ACLs from Cluster

docs/the-descriptor-files.rst, example/descriptor-with-metadata.yaml, src/main/java/com/purbon/kafka/topology/model/Impl/TopicImpl.java, src/main/java/com/purbon/kafka/topology/model/Topic.java, src/main/java/com/purbon/kafka/topology/model/User.java, src/main/java/com/purbon/kafka/topology/serdes/TopicCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/resources/descriptor-with-metadata.yaml
This implement support for #199.  
New feature
Not supported.
* **Does this PR introduce a breaking change?** 
No
closes #199
=> Add topology metadata support for topics and users

pom.xml, src/main/java/com/purbon/kafka/topology/backend/FileBackend.java, src/main/java/com/purbon/kafka/topology/backend/RedisBackend.java, src/test/java/com/purbon/kafka/topology/TopologyValidationTest.java, src/test/java/com/purbon/kafka/topology/backend/FileBackendTest.java, src/test/java/com/purbon/kafka/topology/backend/RedisBackendTest.java
- [ x] The commit messages are descriptive
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] An issue has been created for the pull requests. Some issues might require previous discussion.
Bug fix
https://github.com/kafka-ops/kafka-topology-builder/issues/209
No.
Probably not a good idea to use spaces for separators anyway, but I kept …
=> File backend fix

pom.xml, src/main/java/com/purbon/kafka/topology/JulieOps.java, src/test/java/com/purbon/kafka/topology/schemas/SchemaRegistryManagerTest.java, src/test/resources/schemas/test-backward-compatible.avsc, src/test/resources/schemas/test-backward-compatible.json, src/test/resources/schemas/test-backward-compatible.proto, src/test/resources/schemas/test-forward-compatible.avsc, src/test/resources/schemas/test-forward-compatible.json, src/test/resources/schemas/test-forward-compatible.proto, src/test/resources/schemas/test.avsc, src/test/resources/schemas/test.json, src/test/resources/schemas/test.proto
An enhancement of schema serialization format support.
https://github.com/kafka-ops/julie/issues/215
Nop
=> Add support for JsonSchema and Protobuf when working with Schema Registry

src/main/java/com/purbon/kafka/topology/backend/FileBackend.java, src/test/java/com/purbon/kafka/topology/ExecutionPlanTest.java, src/test/java/com/purbon/kafka/topology/PrincipalManagerTest.java, src/test/java/com/purbon/kafka/topology/backend/FileBackendTest.java
=> Fix FileBackend bug in windows to use FileWriter due to closing problems with RandomAccessFile

src/main/java/com/purbon/kafka/topology/serdes/TopologyCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/resources/descriptor-without-topics.yml
=> Add more clear error for descriptor files without the topics section in the serdes

.github/workflows/ci-integration-test-legacy.yml, .github/workflows/ci-integration-test-main.yml, .github/workflows/ci-unit-test-legacy.yml, .github/workflows/ci-unit-test-main.yml, .github/workflows/nightly-artifacts-build.yml, .github/workflows/release-artifacts-build-legacy.yml, .github/workflows/release-docker-legacy.yml
Add jobs for the 2.x with java8
=> Update main CI jobs

docs/config-values.rst, src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/AccessControlProviderFactory.java, src/main/java/com/purbon/kafka/topology/Configuration.java, src/main/java/com/purbon/kafka/topology/Constants.java, src/main/java/com/purbon/kafka/topology/JulieOps.java, src/main/java/com/purbon/kafka/topology/PrincipalProviderFactory.java, src/main/java/com/purbon/kafka/topology/api/mds/MDSApiClientBuilder.java, src/test/java/com/purbon/kafka/topology/AccessControlManagerTest.java, src/test/java/com/purbon/kafka/topology/AccessControlProviderFactoryTest.java, src/test/java/com/purbon/kafka/topology/AclsBindingsBuilderTest.java, src/test/java/com/purbon/kafka/topology/ConfigurationTest.java, src/test/java/com/purbon/kafka/topology/JulieOpsTest.java, src/test/java/com/purbon/kafka/topology/PrincipalManagerTest.java, src/test/java/com/purbon/kafka/topology/RbacProviderTest.java, src/test/java/com/purbon/kafka/topology/TopicManagerTest.java, src/test/java/com/purbon/kafka/topology/TopicTest.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/java/com/purbon/kafka/topology/TopologyValidationTest.java, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/SchemaRegistryManagerIT.java, src/test/java/com/purbon/kafka/topology/integration/TopicManagerIT.java
=> Skip Julie principal when dealing with ACLs, if present

src/main/java/com/purbon/kafka/topology/actions/topics/SyncTopicAction.java, src/main/java/com/purbon/kafka/topology/api/adminclient/TopologyBuilderAdminClient.java, src/main/java/com/purbon/kafka/topology/model/Impl/TopicImpl.java, src/main/java/com/purbon/kafka/topology/model/Topic.java, src/main/java/com/purbon/kafka/topology/validation/topic/PartitionNumberValidation.java, src/main/java/com/purbon/kafka/topology/validation/topic/ReplicationFactorValidation.java, src/test/java/com/purbon/kafka/topology/TopicManagerTest.java, src/test/java/com/purbon/kafka/topology/integration/TopicManagerIT.java
Objective:
* use cluster level defaults for partitionCount and replicationFactor for topics.
fixes #243 #87
=> update topic partition and replication factor to use cluster defaults  if nothing is available in the topology

src/main/java/com/purbon/kafka/topology/PrincipalManager.java
=> add control center and schema registry principals on the platform level to be handled by the service account manager as well

src/test/java/com/purbon/kafka/topology/integration/containerutils/AlternativeKafkaContainer.java, src/test/java/com/purbon/kafka/topology/integration/containerutils/ContainerTestUtils.java, src/test/java/com/purbon/kafka/topology/integration/containerutils/SaslPlaintextKafkaContainer.java
Ref https://github.com/kafka-ops/julie/pull/212 which updated the Kafka version.
This PR updates the cp-kafka version used in integration tests to match the version targeted in the pom file.
=> Sync integration test Kafka version with the version in the pom.

src/main/java/com/purbon/kafka/topology/api/mds/MDSApiClient.java, src/main/java/com/purbon/kafka/topology/api/mds/RbacResourceType.java, src/main/java/com/purbon/kafka/topology/api/mds/Response.java, src/main/java/com/purbon/kafka/topology/roles/RBACProvider.java, src/main/java/com/purbon/kafka/topology/utils/JSON.java, src/test/java/com/purbon/kafka/topology/integration/RBACPRoviderRbacIT.java
=> Amend listAcls function for rbac providers so delete and listing after execution works as well when using RBAC

src/main/java/com/purbon/kafka/topology/TopologyObjectBuilder.java, src/test/java/com/purbon/kafka/topology/JulieOpsTest.java, src/test/java/com/purbon/kafka/topology/integration/RBACPRoviderRbacIT.java, src/test/resources/dir_with_subdir/descriptor-with-others.yml, src/test/resources/dir_with_subdir/descriptor.yaml, src/test/resources/dir_with_subdir/schemas/bar-key.avsc, src/test/resources/dir_with_subdir/schemas/bar-value.avsc
=> (Fix) Skip subdir's in case of loading multiple topologies from a directory

release/docker/Dockerfile
Upgrade the docker image to fix CVEs
The 11 version doesn't have security fixes
Should have most updates CVE fixes
No
=> Upgrade to latest version of JDK11 in Docker Image

src/main/java/com/purbon/kafka/topology/roles/rbac/RBACBindingsBuilder.java
=> Enable group acls for consumers within the rbac bindings api

src/main/java/com/purbon/kafka/topology/roles/acls/AclsBindingsBuilder.java, src/test/java/com/purbon/kafka/topology/integration/AccessControlManagerIT.java
=> Add missing ACLS for Control Center to work properly

src/main/java/com/purbon/kafka/topology/clients/JulieHttpClient.java, src/test/java/com/purbon/kafka/topology/integration/ConnectApiClientIT.java
=> Fix: ssl context contruction when no ssl configuration is provided.

src/main/java/com/purbon/kafka/topology/backend/BackendState.java, src/main/java/com/purbon/kafka/topology/backend/FileBackend.java, src/main/java/com/purbon/kafka/topology/utils/JSON.java, src/test/java/com/purbon/kafka/topology/backend/FileBackendTest.java
See [closed PR#317](https://github.com/kafka-ops/julie/pull/317)
=> Recreate PR#317

src/main/java/com/purbon/kafka/topology/serdes/TopologyCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/TopologyObjectBuilderTest.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/resources/descriptor-only-conn.yaml
=> Make topics an optional parameters, so only connector topologies can easier exist

src/main/java/com/purbon/kafka/topology/serdes/TopologyCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/TopologyObjectBuilderTest.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/resources/descriptor-only-platform.yaml
=> Make projects an optional field, so platform only topologies are easier possible

src/main/scripts/preinstall.sh
Add verification code in the rpm to be sure java is installed and the version is at least 11.
close #363
=> Add pre install hook verification for requirement java 

docs/futures/what-ksql-management.rst, docs/how-to-run-it.rst, docs/index.rst
fixes #380 
This make sure that `artefacts` is used rather than `artifacts` consistently in docs and examples
=> Correct artifacts -> artefacts

src/main/java/com/purbon/kafka/topology/CommandLineInterface.java, src/main/java/com/purbon/kafka/topology/backend/KafkaBackend.java, src/main/java/com/purbon/kafka/topology/serdes/TopologyCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java
two small fixes, the title is explanatory.
=> KafkaBackendFix (state initialisation) and exit JVM if exception if raised

example/topology-builder-sasl-plain.properties, src/main/java/com/purbon/kafka/topology/api/connect/KConnectApiClient.java, src/main/java/com/purbon/kafka/topology/serdes/TopologyCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java, src/test/resources/descriptor-connector-alone.yaml
=> fix/handling of connectors only without defining ACLs for them in the topology section

example/topology-builder-rbac.properties, src/main/java/com/purbon/kafka/topology/api/mds/MDSApiClient.java, src/main/java/com/purbon/kafka/topology/api/mds/RequestScope.java, src/main/java/com/purbon/kafka/topology/roles/RBACProvider.java, src/main/java/com/purbon/kafka/topology/serdes/TopologyCustomDeserializer.java, src/test/java/com/purbon/kafka/topology/TopologySerdesTest.java
=> fix: delete problem on resource used from the rbac api (wrong resource type)

src/main/java/com/purbon/kafka/topology/model/users/Producer.java, src/main/java/com/purbon/kafka/topology/roles/rbac/RBACBindingsBuilder.java, src/test/java/com/purbon/kafka/topology/integration/RBACPRoviderRbacIT.java, src/test/java/com/purbon/kafka/topology/integration/containerutils/TestProducerConsumerQuota.java
=> Add producer Idempotence permissions to Confluent RBAC

src/main/java/com/purbon/kafka/topology/roles/rbac/RBACBindingsBuilder.java, src/test/java/com/purbon/kafka/topology/integration/RBACPRoviderRbacIT.java
=> fix: issue with connector and subject permissions being ignored when more than one

pom.xml
Update log4j2 to the latest 2.16.0 version
https://github.com/kafka-ops/julie/issues/424
No new behaviour introduced
No breaking changes introduced
N/A
close #424
=> Bump log4j from 2.13.3 to 2.17.0

docs/futures/what-principal-management.rst, src/main/java/com/purbon/kafka/topology/AbstractPrincipalManager.java, src/main/java/com/purbon/kafka/topology/Configuration.java, src/main/java/com/purbon/kafka/topology/Constants.java, src/main/java/com/purbon/kafka/topology/JulieOps.java, src/main/java/com/purbon/kafka/topology/PrincipalProvider.java, src/main/java/com/purbon/kafka/topology/actions/accounts/ClearAccounts.java, src/main/java/com/purbon/kafka/topology/api/ccloud/CCloudApi.java, src/main/java/com/purbon/kafka/topology/serviceAccounts/CCloudPrincipalProvider.java, src/main/java/com/purbon/kafka/topology/serviceAccounts/VoidPrincipalProvider.java, src/main/resources/reference.conf, src/test/java/com/purbon/kafka/topology/PrincipalManagerTest.java
=> Bring Principal Management for Confluent Cloud out of Experimental into Production ready feature

docs/futures/run-validations.rst, src/main/java/com/purbon/kafka/topology/Constants.java, src/main/java/com/purbon/kafka/topology/TopologyValidator.java, src/main/java/com/purbon/kafka/topology/validation/topic/ConfigurationKeyValidation.java, src/main/java/com/purbon/kafka/topology/validation/topic/PartitionNumberValidation.java, src/main/java/com/purbon/kafka/topology/validation/topic/ReplicationFactorValidation.java, src/main/java/com/purbon/kafka/topology/validation/topic/TopicNameRegexValidation.java, src/main/java/com/purbon/kafka/topology/validation/topology/CamelCaseNameFormatValidation.java, src/test/java/com/purbon/kafka/topology/TopologyValidationTest.java
=> Fix config passing for topology validator for regular expressions

.github/workflows/ci-unit-test-main.yml, src/main/java/com/purbon/kafka/topology/backend/S3Backend.java, src/test/java/com/purbon/kafka/topology/integration/backend/S3BackendIT.java
=> Clarify S3 Backend IT test

src/main/java/com/purbon/kafka/topology/model/cluster/ServiceAccountV1.java, src/main/java/com/purbon/kafka/topology/roles/CCloudAclsProvider.java, src/main/java/com/purbon/kafka/topology/utils/CCloudUtils.java, src/test/java/com/purbon/kafka/topology/utils/CCloudUtilsTest.java
=> Refactor and add tests related to Confluent Cloud service account translation feature

docs/the-descriptor-files.rst, docs/topologies/descriptor.schema.json, docs/topologies/descriptor.yaml, src/main/java/com/purbon/kafka/topology/model/Project.java
=> Add a JSON schema description of the topology/descriptor file sintax

src/main/java/com/purbon/kafka/topology/Configuration.java, src/main/java/com/purbon/kafka/topology/TopicManager.java, src/test/java/com/purbon/kafka/topology/ConfigurationTest.java, src/test/java/com/purbon/kafka/topology/TestTopologyBuilder.java
=> Add Kafka Streams applicationId as internal topics, if available

src/main/java/com/purbon/kafka/topology/JulieOpsAuxiliary.java, src/main/java/com/purbon/kafka/topology/TopicManager.java, src/main/java/com/purbon/kafka/topology/model/users/ConfluentCloudPrincipal.java, src/test/java/com/purbon/kafka/topology/TopicManagerTest.java, src/test/java/com/purbon/kafka/topology/utils/CCloudUtilsTest.java
=> Fix Confluent Cloud Translation mechanism when the Service Account does not have a type prefix (default user)

example/topology-builder-rbac-tls.properties, pom.xml, src/main/java/com/purbon/kafka/topology/Configuration.java, src/main/java/com/purbon/kafka/topology/Constants.java, src/main/java/com/purbon/kafka/topology/JulieOps.java, src/main/java/com/purbon/kafka/topology/JulieOpsAuxiliary.java, src/main/resources/reference.conf
=> Allow setting Root log level as debug in the code

src/main/java/com/purbon/kafka/topology/Constants.java, src/main/java/com/purbon/kafka/topology/validation/topic/MinInSyncReplicasValidation.java, src/main/java/com/purbon/kafka/topology/validation/topic/PartitionNumberValidation.java, src/main/java/com/purbon/kafka/topology/validation/topic/ReplicationFactorValidation.java, src/main/resources/reference.conf, src/test/java/com/purbon/kafka/topology/validation/topic/MinInSyncReplicasValidationTest.java, src/test/java/com/purbon/kafka/topology/validation/topic/PartitionNumberValidationTest.java, src/test/java/com/purbon/kafka/topology/validation/topic/ReplicationFactorValidationTest.java
* Parametrited replication factor
* Parametrized partitions count 
* Min insync replicas gte replication factor -1
=> Add extra validations for topics 

src/test/java/com/purbon/kafka/topology/integration/RBACPRoviderRbacIT.java
=> Verify schemas deletion process successfully

src/main/java/com/purbon/kafka/topology/AccessControlManager.java, src/main/java/com/purbon/kafka/topology/roles/ResourceFilter.java, src/test/java/com/purbon/kafka/topology/ResourceFilterTest.java
=> Extend ResourceFilter rules to be more precises for AccessControlManager (ACLs/RBAC)

src/main/java/com/purbon/kafka/topology/CCloudApiReprod.java, src/main/java/com/purbon/kafka/topology/api/ccloud/CCloudApi.java, src/main/java/com/purbon/kafka/topology/api/mds/Response.java, src/test/java/com/purbon/kafka/topology/api/ccloud/CCloudApiTest.java
=> Fix pagination issue when listing service accounts for confluent cloud
